### ISSUE TITLE
Cookie Monster's notification sounds do not respect the vanilla volume setting

### ISSUE THREAD

**Issue by staticvariablejames** [Aktanusa/CookieMonster#437] opened 2020-12-10 21:48 UTC
Each notification sound has an option to adjust the volume, but they all ignore, for example, if the vanilla volume is set to 0.

(From <https://www.reddit.com/r/CookieClicker/comments/kaefd4>)

**Comment by DanielNoord** [comment] 2020-12-10 22:18
Thanks for making an issue, I do not always see posts on the reddit!

I don't think we will push a hot fix for this issue but rather fix it with the implementation of #26 (where you gave a good suggestion I saw).
#26 is scheduled for next release so the reporter shouldn't have to wait too long!

**Comment by DanielNoord** [comment] 2020-12-10 22:29
By the way, have you tested this yourself?
After a quick look and test I wasn't able to easily reproduce this. They seem to work fine for me.

I don't really know where to look for possible issues as I am not quite sure what could be the problem and not able to reproduce it. The new sounds use the same functions as the old ones and we did include "standard values" whenever they were not configured by the user themselves (standard value is 100%).

**Comment by staticvariablejames** [comment] 2020-12-10 22:38
The specific test I did was with the Garden. Using the debug upgrade "Turbo-charged soil", I get a notification every second, and the notification is as loud as possible even if I set the Vanilla volume slider to 0. The bug exists in <https://cdn.rawgit.com/Aktanusa/CookieMonster/dev/CookieMonster.js>.

(I only referenced that Reddit post because it was not me who found the bug...)

**Comment by DanielNoord** [comment] 2020-12-10 22:42
Ah okay! I am pretty sure the function in CookieMonster that creates the sounds currently does not check the Vanilla volume slider.
This is something we should clearly add.
I think that would also solve this bug as the individual volume settings per notification seem to work as intended.

**Comment by DanielNoord** [comment] 2020-12-13 21:15
This should now be fixed! :)

**Closed** 2020-12-13 21:14 UTC
Labels: Bug
