### ISSUE TITLE
Exclude buildings from the purchase index

### ISSUE THREAD

**Issue by Nyhilo** [Aktanusa/CookieMonster#553] opened 2021-02-03 16:50 UTC
Currently, my strategy includes keeping my Wizard towers at low numbers so I can use them to double up on Hand of Fate spells.

* Keep your Wizard Towers at 430
* When a frenzy cookies shows up:
    * Cast Hand of Fate
    * Sell 400 Towers
    * Cast Hand of Fate again

Because of this, Wizard Towers are always my least-purchased building and are always the green option for buying with CookieMonster's price index calculations.

I would still like to take advantage of the index for other buildings while doing this strategy, so it would be helpful to exclude some buildings from the calculation so their numbers aren't accounted for when doing the color highlighting.

Attached screenshots show the current implementation compared to a mockup of what this feature might look like
<p float="left">
  <img src="https://user-images.githubusercontent.com/11170845/106779481-447ee000-6604-11eb-9299-c7b2913651a6.png" width="200" />
  <img src="https://user-images.githubusercontent.com/11170845/106780187-fa4a2e80-6604-11eb-8d63-5dfe7496806f.png" width="200" /> 
</p>

**Comment by DanielNoord** [comment] 2021-02-03 17:14
This is actually a duplicate of #155 (and indeed a very useful function).
It is planned for the next release but I can't give a release date just yet.

**Closed by DanielNoord** 2021-02-03 17:14 UTC
Labels: Enhancement

**Comment by Nyhilo** [comment] 2021-02-03 18:38
Ah great to see! Apologies for not looking harder for an existing thread.

**Comment by DanielNoord** [comment] 2021-02-03 19:09
No problem! Always happy to see people finding the GitHub, that's often the most difficult step :)
