### ISSUE TITLE
Release version does not show any green buildings or blue technologies

### ISSUE THREAD

**Issue by dwblaikie** [Aktanusa/CookieMonster#708] opened 2021-03-20 18:05 UTC
**Describe the bug**
Based on using the mod for the last few days (prior to the bug showing up) there was always one building highlighted in green - the building with the best (lowest) PP. Now I only see orange and yellow coloured buildings (and purple) - there's no green building.

**To Reproduce**
I think I upgraded to the latest Cookie Monster earlier today and since then haven't seen any buildings highlighted in green - only yellow and orange.

**Screenshots**
![image](https://user-images.githubusercontent.com/20646145/111881034-ef0c5180-896b-11eb-88a0-ac1e7a2aef9a.png)

**Save file**
```
Mi4wMzF8fDE2MTU3NjEyODEyMTA7MTYxNTc2MTI4MTIxMDsxNjE2MjYzMzAxODIyO0pvaG5ueSBIb3Rib2R5O3JsYmV4fDAxMTExMDAxMDAwMTAwMTEwMTAxMHwxMzI5NDE3Mzc3NTY1NC4zNzs0MzE0MjMxMDQ0NzIwOTIyLjU7NzA0NDI7NTk4OzEzMTIwMTc2MzQ0MTc5MTQ7NjE4OzA7MDswOzA7MDswOzA7MDswOzU5ODswOzA7MDswOzA7MDs7MDswOzA7MDswOzA7MDstMTstMTstMTstMTstMTswOzA7MDswOzUwOzA7MDswOzY7MTYxNjE5NjA3MjcxNjswOzA7OzQxOzA7MDszOTI3NDI2NTkxNi44MzkyMzt8MTM2LDEzNiwzNTMwNTQ1MjU0ODcsMCwsMCwxMzY7MTcxLDE3MSwyNTM1ODc0Njc4ODI3LDAsLDAsMTcxOzEwMCwxMDAsMjkwMjQyMDYxNjYsMCwsMCwxMDA7ODQsODQsOTA0NDA2NDY5MTUsMCwsMCw4NDs3NSw3NSwzODI1ODAyMzM3NDUsMCwsMCw3NTs2OSw2OSwxNjQwODUxNTQyNTc2LDAsLDAsNjk7NjIsNjIsNjQ3MDE4Mjc5NjU3NCwwLCwwLDYyOzU0LDU0LDE4NDkyMzMxOTk3MTU1LDAsLDAsNTQ7NDIsNDIsNzI4MzA1MjEzNjUzMTksMSwsMCw0MjszNSwzNSwyNzQzOTc2NzQyNTM3NTYsMSwsMCwzNTszMCwzMCw1NjM3OTY4NzgwNzMwNDIsMiwsMCwzMDsxOCwxOCw3MjU5MjYzMjMxMjkyNjEsMSwsMCwxODs0LDQsMzQ0MTI2OTIwMDA1Mzk0LDAsLDAsNDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwO3wxMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTEwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTAwMTExMTAwMDAwMDAwMTEwMDExMTExMTAwMTEwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMTAxMDEwMTAwMDAwMTExMTAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMTAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMDAwMDExMTExMTExMDAwMDExMTExMTExMDAwMDExMTExMTAwMDAwMDEwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTF8MTExMTExMTExMTAwMDAwMDExMTExMTExMTEwMDAwMTExMTExMTEwMDExMTExMTExMDExMDEwMDEwMDEwMDEwMDAwMDExMTAwMTExMTAxMDAwMTAwMDAwMTAwMDAwMTAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAxMTEwMDAxMTAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMHx8Q29va2llTW9uc3Rlcjp7InNldHRpbmdzIjp7IkJvdEJhciI6MCwiVGltZXJCYXIiOjEsIlRpbWVyQmFyUG9zIjowLCJUaW1lckJhck92ZXJsYXkiOjAsIkJ1aWxkQ29sb3IiOjEsIkJ1bGtCdWlsZENvbG9yIjowLCJVcEJhckNvbG9yIjoyLCJVcGdyYWRlQmFyRml4ZWRQb3MiOjEsIkNhbGNXcmluayI6MCwiQ1BTTW9kZSI6MCwiQXZnQ1BTSGlzdCI6MywiQXZnQ2xpY2tzSGlzdCI6MCwiQ29sb3JQUEJ1bGtNb2RlIjoxLCJQUEV4Y2x1ZGVUb3AiOjAsIlBQU2Vjb25kc0xvd2VyTGltaXQiOjAsIlBQT25seUNvbnNpZGVyQnV5YWJsZSI6MCwiVG9vbFdhcm5Cb24iOjAsIlRpdGxlIjoxLCJHZW5lcmFsU291bmQiOjEsIkdDTm90aWZpY2F0aW9uIjoxLCJHQ0ZsYXNoIjoxLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MTAwLCJHQ1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvNjYvNjY3MTdfOTMxNjU1LWxxLm1wMyIsIkZvcnR1bmVOb3RpZmljYXRpb24iOjEsIkZvcnR1bmVGbGFzaCI6MSwiRm9ydHVuZVNvdW5kIjoxLCJGb3J0dW5lVm9sdW1lIjoxMDAsIkZvcnR1bmVTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE3NC8xNzQwMjdfMzI0MjQ5NC1scS5tcDMiLCJTZWFOb3RpZmljYXRpb24iOjEsIlNlYUZsYXNoIjoxLCJTZWFTb3VuZCI6MSwiU2VhVm9sdW1lIjoxMDAsIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkdhcmRTb3VuZCI6MSwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MSwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiV3JpbmtsZXJNYXhTb3VuZCI6MSwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjAsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJUb29sdGlwUGxvdHMiOjEsIkRyYWdvbkF1cmFJbmZvIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJVcFN0YXRzIjoxLCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIkdyaW1vaXJlQmFyIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIlNjYWxlIjoyLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiQ29sb3JzIjp7IkJsdWUiOiIjNGJiOGYwIiwiR3JlZW4iOiIjMDBmZjAwIiwiWWVsbG93IjoiI2ZmZmYwMCIsIk9yYW5nZSI6IiNmZjdmMDAiLCJSZWQiOiIjZmYwMDAwIiwiUHVycGxlIjoiI2ZmMDBmZiIsIkdyYXkiOiIjYjNiM2IzIiwiUGluayI6IiNmZjE0OTMiLCJCcm93biI6IiM4YjQ1MTMifSwiU29ydEJ1aWxkaW5ncyI6MSwiU29ydFVwZ3JhZGVzIjowLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkJ1bGtCdXlCbG9jayI6MCwiSGVhZGVyIjp7IkJhcnNDb2xvcnMiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGF0aW9uIjoxLCJNaXNjZWxsYW5lb3VzIjoxLCJMdWNreSI6MSwiQ2hhaW4iOjEsIlNwZWxscyI6MSwiR2FyZGVuIjoxLCJQcmVzdGlnZSI6MSwiV3JpbmsiOjEsIlNlYSI6MSwiTWlzYyI6MSwiSW5mb1RhYiI6MX0sIlBQRGlzcGxheVRpbWUiOjAsIlBQUmlnaWRlbE1vZGUiOjAsIlRvb2x0aXBQYW50aGVvbiI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MH0sInZlcnNpb24iOiIyLjAzMS42In07%21END%21
```

**Comment by dwblaikie** [comment] 2021-03-20 18:07
Oh, the screenshot was bad (because the macos shortcut key - shift+command+3 of course changed my building listing. Here's a better one)
![image](https://user-images.githubusercontent.com/20646145/111881136-6641e580-896c-11eb-8ca7-69953f6cf6f3.png)

**Comment by DanielNoord** [comment] 2021-03-21 12:54
This is a duplicate of #703 and some of the other similar issues.
There is still a green building but it is no longer a "buy 1" option. In your particular save it is better to buy 10 shipments than any of the other buildings. You will that shipments are colour coded accordingly in the buy 10 column.

**Closed by DanielNoord** 2021-03-21 12:54 UTC
Labels: Bug

**Comment by dwblaikie** [comment] 2021-03-21 15:48
Ah. Hmm - might be worth a write up somewhere explaining why it's worse to buy 1 than 10? I don't quite understand why that would be the case. Except if it's for "but buying 10 gets you over an achievement milestone and that's valuable"?

Should/could I file a separate feature request for the 1/10/100s to be colour coded too, then? So you know where to look for the green thing that's otherwise hiding in one of those other tabs/columns?

**Comment by DanielNoord** [comment] 2021-03-21 15:55
That is indeed often the reason for buy 10 being better.
Colour coding the 1/10/100s green is actually quite a good idea, however I do think this should be a toggle and a setting. Just having this as a possible setting might also help people understand where they could look if they can't find a green building.
