### ISSUE TITLE
New Krumblor "Dragon Scale" upgrade breaks everything

### ISSUE THREAD

**Issue by andybish** [Aktanusa/CookieMonster#310] opened 2020-09-13 14:50 UTC
As soon as I purchase the new upgrade "Dragon Scale", a random drop from petting Krumblor that's supposed to just increase cookie production 3%, almost all PP values go negative, as does reset bonus income.

**Comment by Aktanusa** [comment] 2020-09-13 14:58
Thanks for the heads up.  I really have not been working on the addon recently since my priorities changed.  I hope to change it back soon, but I have no ETA.  My life is a bit of a mess right now.

**Comment by FWDekker** [comment] 2020-11-02 16:32
This is a duplicate of #302, just like #306 and #317.

@Aktanusa If you want you can pin #302 (and give it a better title) to prevent more duplicate issues.

**Comment by DanielNoord** [comment] 2020-11-23 13:50
We will now use #317 to discuss any missing upgrades or items as a result of CookieMonster not being updated for CookeClicker 2.031.

**Closed by DanielNoord** 2020-11-23 13:50 UTC
