### ISSUE TITLE
Time until next Heavenly Chip

### ISSUE THREAD

**Issue by DAIstian** [Aktanusa/CookieMonster#194] opened 2018-05-16 12:06 UTC
It would be quite useful if there was a calculation shown in stats/hovering over the legacy button that shows how much time there is left until you get the next heavenly chip at your current CpS.

**Comment by Aktanusa** [comment] 2018-05-16 13:12
Hmm, I guess.  Is it for the special prestige upgrades?

**Comment by DanielNoord** [comment] 2020-11-26 10:51
This is a duplicate of #80

**Closed by DanielNoord** 2020-11-26 10:51 UTC
