### ISSUE TITLE
Conjure Baked Goods spell tooltip gives wrong estimate when Wrinklers are present

### ISSUE THREAD

**Issue by jeffslutzky** [Aktanusa/CookieMonster#1074] opened 2022-05-09 14:11 UTC
### Bug description

When I have wrinklers present, the Conjure Baked Goods spell bases its prediction on the withered CpS, but when I actually click on the spell, it gives me half an hour of cookies based on un-withered CpS. So Conjure Baked Goods is under-predicting the number of cookies I will receive.

### To reproduce

(1) Have some wrinklers present

(2) Click on Conjure Baked Goods spell in Grimoire

(3) Note the total number of cookies predicted vs. total number of cookies actually gained

### Browser / Steam / Version

Browser v.2031

**Comment by MadeOfMagicAndWires** [comment] 2022-05-31 19:40
Duplicate of #1049

**Comment by DanielNoord** [comment] 2022-06-03 10:21
@jeffslutzky #1049 has been fixed. Could you check if your issue has also been fixed? I don't think this is actually a duplicate, but I want to be sure!

**Comment by jeffslutzky** [comment] 2022-06-03 13:49
Unfortunately it looks like it's still not working for me. Here's a screenshot.

![cc](https://user-images.githubusercontent.com/13684936/171867193-7d0586b9-38d8-4bcc-89e1-94d980797324.jpg)
.

**Closed as completed** 2022-06-04 08:42 UTC
Labels: Bug
