### ISSUE TITLE
Negative PP

### ISSUE THREAD

**Issue by Kermamrek** [Aktanusa/CookieMonster#119] opened 2017-07-11 06:42 UTC
I was playing on the 2.0032 beta for a few days and everything was working totally fine until I randomly bought an extra 10 cursors and suddenly half my buildings went into the negatives with their PP, instantly putting the "most negative" up at the top of the list constantly and making the calculations completely wrong.
![2017-07-11 02_36_37](https://user-images.githubusercontent.com/7284256/28054164-e66673d2-65e1-11e7-86b8-2368c4142c4e.png)
Buying in tens fixes this, but if you buy ten in one increments it doesn't fix itself which leads me to believe it's a bug rather than some production weirdness going on.
![2017-07-11 02_38_19](https://user-images.githubusercontent.com/7284256/28054234-22a3a536-65e2-11e7-80c0-051dbe66d41e.png)
if I buy a group of 10 all that happens is it temporarily fixes itself for that building and just jumps to another building with negative PP
Buying upgrades sometimes fixes it, but most of the time it just changes other buildings to negative in it's place.
![2017-07-11 02_41_14](https://user-images.githubusercontent.com/7284256/28054337-74045dd0-65e2-11e7-98ce-0a32b25c129c.png)
Fiddling with average/current cps calculation settings does nothing, doesn't change PP in the slightest.

**Comment by schmidty749** [comment] 2017-07-12 14:07
Sugar lumps seem to not be supported, so when calculating efficiency the new cps after a purchase doesn't include sugar lump effects. If the purchase has less of an impact than sugar lumps it sees the new cps as lower than the current one, resulting in negative pp.  Is this plugin still maintained?

**Comment by Aktanusa** [comment] 2017-07-12 14:31
Sorry, on vacation right now.  I'll take a look when I get back.  It is still beta, right?

**Comment by schmidty749** [comment] 2017-07-13 16:00
It is still beta. Supporting only sugar lumps should be an easy fix, but I'm not sure what else is added in beta that can break the plug in.

**Comment by vogon** [comment] 2017-07-15 22:49
just as an update, this issue hit the main release today in 2.0034.  I've never contributed to CM before so don't count on it, but I'll take a look to see if I can whip up a quick fix for sugar lumps at least.

**Comment by Mitsunee** [comment] 2017-07-15 23:07
I can pretty much confirm that this issue is caused by sugar lumps. They improve CpS by leveling up towers which then confuses CM. Haven't found the minigames and such yet, so I have no idea if there's more things that need fixing. To confirm this specific issue I just leveled up my Prisms once and got the behaviour shown above.

**Comment by vogon** [comment] 2017-07-15 23:31
done with a quick fix that just accounts for sugar lump bonuses at https://cdn.rawgit.com/vogon/CookieMonster/776909c31902c30ddd5cae0732645ba51ba06b6a/CookieMonster.js.  (https://github.com/vogon/CookieMonster/tree/v2_0034 is the fork/branch if you want to make sure I didn't sneak anything evil in there.)

**Comment by Aktanusa** [comment] 2017-07-19 01:25
Okay, thanks @vogon.  I'm back and I'll take a look at the CC changes and your fixes.

**Comment by Aktanusa** [comment] 2017-07-19 19:02
Fixed in Version 2.0034.1

**Closed by Aktanusa** 2017-07-19 19:02 UTC
Labels: bug

**Comment by Anahkiasen** [comment] 2017-07-19 20:42
Thanks a lot o/
