### ISSUE TITLE
Show seeds I have not yet unlocked

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#596] opened 2021-02-21 17:54 UTC
As I'm working to unlock seeds in the garden I often cross-reference the wiki to see what other plants there are and what combinations are needed to mutate those new seeds.

In the seed area of the garden add a dividing line below the unlocked seeds. Show ghostly (maybe grayscale or desaturated) images of the other seeds that I have not yet unlocked. When I hover on one of those still-locked seeds show a tooltip window that says what parent or parents are needed to create this seed, and what this seed's effect is. (Help me decide if I want to unlock it and know how to do so.

**Comment by DanielNoord** [comment] 2021-02-21 19:01
Duplicate of #215 
I think you will like [this mod](https://github.com/Acharvak/Cookie-Clicker-Agronomicon).
It does exactly what you ask for and what we discussed in #215. Because it works so well we decided against also adding this function into CookieMonster.

**Closed by DanielNoord** 2021-02-21 19:01 UTC
Labels: Enhancement
