### ISSUE TITLE
Add calculation for chain buying of buildings

### ISSUE THREAD

**Issue by potatonuggetz** [Aktanusa/CookieMonster#228] opened 2018-12-09 15:08 UTC
Currently, it only shows the PP of the next building. It would be great if Cookie Monster could look further ahead in the calculations.

**Comment by Aktanusa** [comment] 2018-12-10 00:40
It does show for buying 10x and buying 100x, but that's pretty limited.  It is planned as mentioned in Issue #4, but it's not easy to implement.

**Comment by DanielNoord** [comment] 2020-11-26 09:44
This is a duplicate of #4

**Closed by DanielNoord** 2020-11-26 09:44 UTC
