### ISSUE TITLE
[Feature request] Show most efficient dragon aura

### ISSUE THREAD

**Issue by egerke28** [Aktanusa/CookieMonster#195] opened 2018-05-18 15:01 UTC
Similarly to the upgrades, it would be great if the tool could show which of the dragon auras that directly improve Cps is the best, or maybe even how long it will take to get back the value of the structure you sacrifice by switching.

Keep up the good word, and thanks for this amazing tool.

**Comment by Aktanusa** [comment] 2018-05-18 15:18
I mean some aura are by chance, like getting Dragon Harvest or Dragonflight.  It's going to be hard to calculate that.  I'm not sure how I would implement this yet.  Thanks for your kind words, though!

**Comment by egerke28** [comment] 2018-05-18 15:41
I was thinking the way upgrades work, ie. only ones that have an easy to calculate cps value (Breath of Milk, Elder battalion, Dragon God...)

**Comment by Aktanusa** [comment] 2018-05-18 22:57
I see, hmm maybe

**Comment by DanielNoord** [comment] 2020-11-26 10:51
This is a duplicate of #185

**Closed by DanielNoord** 2020-11-26 10:51 UTC
Labels: enhancement
