### ISSUE TITLE
Bottom Bar calculations

### ISSUE THREAD

**Issue by Dublekfx** [Aktanusa/CookieMonster#84] opened 2016-05-01 23:34 UTC
Currently, the bottom bar display Bonus Income, Payback Period, and Time left to purchase a single building. However, I usually purchase buildings in groups of 10 or 100. Would it be possible to make the bar reflect the current setting of the buy button, whether it be 1, 10, or 100?

**Comment by Aktanusa** [comment] 2016-05-02 00:11
Hmm, it could be possible, though I guess the stats changing on the building icons themselves weren't good enough?

**Comment by Dublekfx** [comment] 2016-05-02 00:17
I mean they work, but it's nice to see at a glance how long until I can afford 10 of something. I haven't actually looked at your code yet so I don't know how simple or complex it would be to change what's displayed there. If its a lot of work then you're right, its probably not worth it. It just seemed more intuitive to me from a UI standpoint.

**Comment by Aktanusa** [comment] 2016-05-02 00:19
It actually isn't much work minus adding the option for the colors...

**Comment by Dublekfx** [comment] 2016-05-02 00:22
Alright, awesome. Thanks for all your work on the plugin btw. I played for over a year without it, and my life is so much better now for having discovered it.

**Comment by Aktanusa** [comment] 2016-05-02 00:22
Thanks for the kind words =)

**Comment by DanielNoord** [comment] 2020-11-26 09:37
Duplicate of #277.

**Closed by DanielNoord** 2020-11-26 09:37 UTC
Labels: enhancement
