### ISSUE TITLE
[Steam] Duplication of Settings Tab 

### ISSUE THREAD

**Issue by SwiftYoYo** [Aktanusa/CookieMonster#974] opened 2021-09-05 10:34 UTC
**Describe the bug**
The "Cookie Monster Mod Family" tab is duplicated many many times upon changing the volume. (Steam ver.)

**To Reproduce**
The steps needed to reproduce the behavior:
1. Simply change either music or sound volume.

**Screenshots**
Example: https://www.youtube.com/watch?v=jE30l6rZA9c

**Save file**
Save file: https://pastebin.com/cQtbD2XM
```
Mi4wNHx8MTYzMDc1NTcxMzM5NTsxNjMwNzU1NzEzMzk1OzE2MzA4Mzc5MTM4MjY7WW9ZbztpemJsenwxMTExMTEwMTEwMDEwMTExMDEwMTAxMTAwfDM2NTAwMTIwOC41NDgyMTc1OzQ1MTM3ODM4NzAuNTQ0NDc4OzU3ODsxMzszNjMyMzE4LjEzMjc0MTkxNDY7MTc7MDswOzA7MDswOzA7MDswOzA7MTM7MDswOzA7MDswOzA7OzA7MDswOzA7MDswOzA7LTE7LTE7LTE7LTE7LTE7MDswOzA7MDs4ODswOzA7MDswOzE2MzA4MzM5MTg5OTQ7MDswOzsxMDA7MDswOzEwMjQ0ODMuODM2NTk4NTA2NzswO3w4NCw4NCw1OTg1Nzk4NCwwLCwwLDg0OzgzLDgzLDExOTY1ODg2NCwwLCwwLDgzOzUxLDUxLDUxNDkzNDQ2LDAsLDEsNTE7NTEsNTEsMTcwOTkyMDUyLDAsLDEsNTE7MzcsMzcsNTI4Mzk2NDMxLDAsLDEsMzc7MzAsMzAsMTA3MTE3ODA3NywwLCwxLDMwOzEyLDEyLDQwMzc2MTAzOSwwLCwxLDEyOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7MCwwLDAsMCwsMCwwOzAsMCwwLDAsLDAsMDswLDAsMCwwLCwwLDA7fDExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMDExMTExMTExMTExMDExMTAxMDEwMDAxMTEwMDAxMDAwMDAwMDAwMTEwMDAwMDAwMDExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMHwxMTExMTEwMDAwMDAwMDAwMTExMTExMDAwMDAwMDExMTAwMTExMDAwMTEwMTEwMTAwMTEwMDAwMDAwMDAwMDAwMDAwMTEwMDExMDEwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDExMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwfHxDb29raWVNb25zdGVyOnsic2V0dGluZ3MiOnsiQ1BTTW9kZSI6MCwiQXZnQ1BTSGlzdCI6MiwiQXZnQ2xpY2tzSGlzdCI6MCwiQ2FsY1dyaW5rIjowLCJTY2FsZSI6MCwiU2NhbGVEZWNpbWFscyI6MCwiU2NhbGVTZXBhcmF0b3IiOjAsIlNjYWxlQ3V0b2ZmIjo5OTk5OTksIlRpbWVGb3JtYXQiOjEsIkRldGFpbGVkVGltZSI6MCwiUFBEaXNwbGF5VGltZSI6MCwiQnVpbGRDb2xvdXIiOjEsIlBQT25seUNvbnNpZGVyQnV5YWJsZSI6MCwiUFBFeGNsdWRlVG9wIjowLCJQUFJpZ2lkZWxNb2RlIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJDb2xvdXJCbHVlIjoiIzRiYjhmMCIsIkNvbG91ckdyZWVuIjoiIzAwZmYwMCIsIkNvbG91clllbGxvdyI6IiNmZmZmMDAiLCJDb2xvdXJPcmFuZ2UiOiIjZmY3ZjAwIiwiQ29sb3VyUmVkIjoiI2ZmMDAwMCIsIkNvbG91clB1cnBsZSI6IiNmZjAwZmYiLCJDb2xvdXJHcmF5IjoiI2IzYjNiMyIsIkNvbG91clBpbmsiOiIjZmYxNDkzIiwiQ29sb3VyQnJvd24iOiIjOGI0NTEzIiwiQm90QmFyIjowLCJUaW1lckJhciI6MSwiVGltZXJCYXJQb3MiOjAsIlRpbWVyQmFyT3ZlcmxheSI6MSwiQXV0b3NhdmVUaW1lckJhciI6MCwiVXBCYXJDb2xvdXIiOjIsIlVwZ3JhZGVCYXJGaXhlZFBvcyI6MSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjowLCJVcGdyYWRlc05ldmVyQ29sbGFwc2UiOjEsIkRyYWdvbkF1cmFJbmZvIjoxLCJHcmltb2lyZUJhciI6MSwiR0NUaW1lciI6MSwiRmF2aWNvbiI6MSwiV3JpbmtsZXJCdXR0b25zIjoxLCJIaWRlU2VjdGlvbnNCdXR0b25zIjowLCJUb29sdGlwQnVpbGRVcGdyYWRlIjoxLCJUb29sdGlwQW1vciI6MCwiVG9vbFdhcm5MdWNreSI6MCwiVG9vbFdhcm5MdWNreUZyZW56eSI6MCwiVG9vbFdhcm5Db25qdXJlIjowLCJUb29sV2FybkNvbmp1cmVGcmVuenkiOjAsIlRvb2xXYXJuRWRpZmljZSI6MSwiVG9vbFdhcm5Vc2VyIjowLCJUb29sV2FybkJvbiI6MCwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJUb29sdGlwUGxvdHMiOjEsIlRvb2x0aXBQYW50aGVvbiI6MSwiVG9vbHRpcEFzY2VuZEJ1dHRvbiI6MSwiU3RhdHMiOjAsIk1pc3NpbmdVcGdyYWRlcyI6MCwiTWlzc2luZ0FjaGlldmVtZW50cyI6MCwiVXBTdGF0cyI6MCwiSGVhdmVubHlDaGlwc1RhcmdldCI6MSwiU2hvd01pc3NlZEdDIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MSwiQ29sb3VyR0NGbGFzaCI6IiNGRkIzMDAiLCJHQ1NvdW5kIjoxLCJHQ1ZvbHVtZSI6MTAwLCJHQ1NvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvNjYvNjY3MTdfOTMxNjU1LWxxLm1wMyIsIkZvcnR1bmVOb3RpZmljYXRpb24iOjAsIkZvcnR1bmVGbGFzaCI6MSwiQ29sb3VyRm9ydHVuZUZsYXNoIjoiI2ZmZmZmZiIsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MSwiQ29sb3VyU2VhRmxhc2giOiIjZmZmZmZmIiwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6MTAwLCJTZWFTb3VuZFVSTCI6Imh0dHBzOi8vd3d3LmZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMjEvMTIxMDk5XzIxOTMyNjYtbHEubXAzIiwiR2FyZEZsYXNoIjoxLCJDb2xvdXJHYXJkRmxhc2giOiIjZmZmZmZmIiwiR2FyZFNvdW5kIjoxLCJHYXJkVm9sdW1lIjoxMDAsIkdhcmRTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEwMy8xMDMwNDZfODYxNzE0LWxxLm1wMyIsIk1hZ2ljTm90aWZpY2F0aW9uIjowLCJNYWdpY0ZsYXNoIjoxLCJDb2xvdXJNYWdpY0ZsYXNoIjoiI2ZmZmZmZiIsIk1hZ2ljU291bmQiOjEsIk1hZ2ljVm9sdW1lIjoxMDAsIk1hZ2ljU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8yMjEvMjIxNjgzXzEwMTUyNDAtbHEubXAzIiwiV3JpbmtsZXJOb3RpZmljYXRpb24iOjAsIldyaW5rbGVyRmxhc2giOjEsIkNvbG91cldyaW5rbGVyRmxhc2giOiIjZmZmZmZmIiwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiQ29sb3VyV3JpbmtsZXJNYXhGbGFzaCI6IiNmZmZmZmYiLCJXcmlua2xlck1heFNvdW5kIjoxLCJXcmlua2xlck1heFZvbHVtZSI6MTAwLCJXcmlua2xlck1heFNvdW5kVVJMIjoiaHR0cHM6Ly9mcmVlc291bmQub3JnL2RhdGEvcHJldmlld3MvMTUyLzE1Mjc0M18xNTY2My1scS5tcDMiLCJCdWxrQnV5QmxvY2siOjAsIkZhdm91cml0ZVNldHRpbmdzIjoxfSwiaGVhZGVycyI6eyJGYXZvdXJpdGUiOjEsIkNhbGN1bGF0aW9uIjowLCJOb3RhdGlvbiI6MCwiQ29sb3VycyI6MCwiQmFyc0Rpc3BsYXkiOjAsIlRvb2x0aXAiOjAsIlN0YXRpc3RpY3MiOjAsIk5vdGlmaWNhdGlvbiI6MCwiTm90aWZpY2F0aW9uR2VuZXJhbCI6MCwiTm90aWZpY2F0aW9uR0MiOjAsIk5vdGlmaWNhdGlvbkZDIjowLCJOb3RpZmljYXRpb25TZWEiOjAsIk5vdGlmaWNhdGlvbkdhcmQiOjAsIk5vdGlmaWNhdGlvbk1hZ2kiOjAsIk5vdGlmaWNhdGlvbldyaW5rIjowLCJOb3RpZmljYXRpb25Xcmlua01heCI6MCwiTWlzY2VsbGFuZW91cyI6MCwiTHVja3kiOjAsIkNoYWluIjowLCJTcGVsbHMiOjEsIkdhcmRlbiI6MSwiUHJlc3RpZ2UiOjAsIldyaW5rIjoxLCJTZWEiOjAsIkFjaGlldnMiOjAsIk1pc2MiOjAsImluZm9NZW51IjoxLCJvcHRpb25zTWVudSI6MH0sImZhdm91cml0ZVNldHRpbmdzIjpbXSwibG9ja2VkTWluaWdhbWVzIjpbXSwidmVyc2lvbiI6IjIuMDMxLjEwIn07Y29va2llTW9uc3RlckZyYW1ld29yazp7InNldHRpbmdzIjp7fSwiaGVhZGVycyI6eyJpbmZvTWVudSI6MSwib3B0aW9uc01lbnUiOjF9LCJmYXZvdXJpdGVTZXR0aW5ncyI6W119O01FVEE6KmNvb2xlciBzYW1wbGUgbW9kLCpsYW5nIHNhbXBsZSBtb2QsKnNhbXBsZSBtb2QsY29va2llIG1vbnN0ZXI7%21END%21
```

Apart from this the mod works perfectly.

**Comment by DanielNoord** [comment] 2021-09-05 10:43
Duplicate of #961, but I'm keeping this open because of the added save file!
Hopefully I'll able to fix this soon!

**Comment by SwiftYoYo** [comment] 2021-09-06 08:05
Apologies, someone reported abuse to my Pastebin but the save should still work :v

**Comment by DanielNoord** [comment] 2021-09-29 19:12
This should now be fixed! Let me know if there are any remaining problems!

**Closed as completed by DanielNoord** 2021-09-29 19:12 UTC
Labels: Bug
