### ISSUE TITLE
All bonuses are negative in current version

### ISSUE THREAD

**Issue by normann1974** [Aktanusa/CookieMonster#241] opened 2019-03-13 16:50 UTC
After the latest CC update (2.018), CM's calculations are wrong, at least for my game. All "bonus income"s and "Payback period"s are negative:

Example game:

`Mi4wMTh8fDE1NTIxMzgwMTE0NzI7MTM4MTk1MzYwMDAwMDsxNTUyNDk1NzI0MzM5O0phbjt5bnRzc3wwMTExMDAxMDAxMDAwMDEwMDEwMTB8MS4zNjk0OTU5NDI3ODQ1MjA1ZSs0Njs1LjExMTE3MDc5NDgyNDgwOGUrNDc7MTQyMDszMjA3NDsxLjUyNDczNzA2MTc4MDgwNDJlKzQ1OzM4NDM0NDswOzA7My40ODM5MTYyOTcwMzkzOWUrNDg7MzswOzA7MDstMTsxMzY7NTE7My4zMjAzODg3MzMxNDY3OTY0ZSs0Njs2Mjc7MTQ7Mjg7LTE7NTs7NC42NDQ1MzY1MzI5MDQxMzNlKzQyOzI7MTUxNTk2NTIxOTM1Nzs0ODEwNDE2ODg4NDY7MTAzNDkyMzUzMDUxMTswOzA7NTg0OzU4NTs1ODY7ODc7NTg3OzIzOzE1OzE7MTsyMDswOzA7MTA0OzY4NjsxNTUyNDUwNjU1NDQ4OzA7MDs0NzUsNDczLDQ3NCwyMjc7NDE7fDczOSwxMDg5LDIuOTU2MjA5MTA2Nzk4NTI4ZSs0MywwLCwwOzcyNiwxMDc2LDcuNzc5NTg0MTM4NTc0OTY4ZSs0MSwwLCwxOzY3NSwxMDI1LDIuNTYwNDA1ODA0NzMxNTQyNGUrNDIsMTAsMTU1MjQ5NjA2NjU4NToyOjE1NTIxMzg3ODE5MDY6MDoyOjI4NDk6MToxOjE1NTIxMzgwMTE1MjU6IDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEgMTg6MzE6MTg6MjY6MTg6MzE6MTg6Mzc6MTg6NDY6MTg6MzY6MTg6MzU6MTg6MzA6MTg6NDI6MTg6Mzc6MTg6MzA6MTg6MzQ6MTg6NTE6MTg6MzA6MTg6NDY6MTg6Mjc6MTg6Mzk6MTg6MjQ6MTg6MzM6MTg6MzE6MTg6MzU6MTg6MzY6MTg6Mzc6MTg6NTI6MTg6Mzg6MTg6MzI6MTg6Mzk6MTg6MzQ6MTg6MjU6MTg6MzQ6MTg6NDE6MTg6NDI6MTg6Mjk6MTg6NDk6MTg6MzQ6MTg6MzI6LDA7NjY4LDEwMTgsMS44NDI1NTk1NDIwODU2MTA2ZSs0NCwxLCwxOzY1MywxMDAzLDIuNjgyOTk5ODM3OTA1ODA0NGUrNDMsMCwsMTs2MzcsOTg3LDYuMTUxNjg5NTc0NTk5Nzc0ZSs0MiwzLCwxOzYzMCw5ODAsMi43OTU4OTMzMzI3ODU5Mzc1ZSs0Myw2LDgvMC83IDMgMTU1MjE2OTc3Nzc0NiAxLDA7NjA5LDk1OSw5LjE4ODQ5MDg3MDI1NDYzNWUrNDIsMTAsMzkuNTM2NjkwNDc4NzE1NzU1IDY2IDYzMDggMSwwOzU3MSw5MjEsMi44MzkxMjU4MDY3NTE4NjFlKzQyLDEwLCwxOzU2MCw5MTAsMS40NzA3MDY3NDk2NTQyMTA1ZSs0MywxMCwsMTs1NTIsOTAyLDguNjQ3MDIxNTM3NDk4OTA3ZSs0MywxMCwsMTs1MzUsODg1LDUuMDU4NzI0NDczMjg5MzU0ZSs0NCwxMCwsMTs1MTMsODYzLDQuNTkxMzMzNjMwMzUwODU4ZSs0NSwxMCwsMTs1MDgsODU4LDIuNjYzNTc2NTI5NzUwODc3ZSs0NiwxMCwsMTs0ODEsODMxLDIuOTk4NTI5MTYxMzA5ODY0NWUrNDUsMTAsLDE7NDc2LDgyOCwyLjE0ODAzNDc5MzkyMzMzOGUrNDYsMTAsLDE7fDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMDAxMTExMTEwMDAwMDAxMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTAxMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAxMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTF8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTAwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAxMTExMTExMTExMTExMTExMTExMTExMTExMDExMTExMDExMHwxNiw5MDAwLDY4NzUsMTAsMCwwOw%3D%3D%21END%21`

**Comment by Aktanusa** [comment] 2019-03-13 18:06
Duplicate of #239

**Comment by Aktanusa** [comment] 2019-03-13 21:44
Fixed in Version 2.018.1

**Closed by Aktanusa** 2019-03-13 21:44 UTC
Labels: bug, duplicate
