### ISSUE TITLE
No Building is shown as the best PP option (green)

### ISSUE THREAD

**Issue by rexatlanti** [Aktanusa/CookieMonster#720] opened 2021-03-22 11:09 UTC
**Describe the bug**
After while no building available is shown as optimal PP option anymore. There should alsways be an optimal building. I assume it's because I didn't buy the Communal Brainsweep? Since that is shown as blue with a PP of 0, which is far lower than the lowest building option.

**Save file**
```
Mi4wMzF8fDE2MTYzNzY1OTEyODM7MTYxNTUzNjgzOTY0MzsxNjE2NDExMzc4NTc2O0Z1cnN0O3dpcWJjfDExMTExMTAxMTAwMTAxMTAwMTExMHw0LjExNjA5NDQ5MzI3Mzg5NzVlKzMwOzQuMjcxMjY1OTIwNzI2MDI4NmUrMzA7ODg0OzE1NzU7MS40OTA5NTYwNzI5MTQwOTM4ZSszMDsyNzU3OzU7MDsxLjIwMzc5MzQ1NTI5MjkwNDJlKzMwOzE7MDswOzA7LTE7NTs0NDsxLjAxNTExNDMwNTIyMzQwMTNlKzMwOzA7MTQ7NjA7MTU4ODc2NzszO2NocmlzdG1hczsxLjIwNDkzNDU2MTI0OTIwNTRlKzMxOzEyOzEwNjM3Nzc7MjM2MzM7MTA0MDE0NDswOzA7MzIxOzIyNjstMTstMTstMTs1OzE7MDswOzA7MDswOzI7MTI7MTYxNjM1NDQ2NjcxNDswOzA7OzQxOzA7MDs0LjE2MDE1ODIzODAzODIwNmUrMjU7fDM3MywzNzMsMy4xNDExMTQ3MjQwODY2MzRlKzI3LDAsLDAsMzczOzM5MywzOTMsMS44Mjc1MjUxMDY1MzAwNjczZSsyNywwLCwxLDM5MzszMTcsMzE3LDYuNDI4Njg2MzA0Njc5MTQxZSsyMiwzLDE2MTY0MTE0MjMwNzc6NDoxNjE2NDA2MDE0MTI5OjA6Mjo3NToxOjA6MTYxNjM3NjU5MTMwNjogMTExMDAwMDAwMDAxMTEwMDAwMDAwMDAxMDAwMDAwMDAwMCAwOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDoxOjQ5OjA6MDowOjA6MDowOjA6MDowOjA6MTo0ODowOjA6MDowOjA6MDowOjA6MDowOjE6NDk6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDowOjA6MDosMCwzMTc7MzAwLDMwMCwxLjEyNTM0NTIwOTg3Mjk4NWUrMjUsMCwsMSwzMDA7MjgyLDI4MywzLjY5MDA5OTA3MzI1MTcwNjJlKzIyLDAsLDEsMjgyOzI2NiwyNjYsOS4yNTYwNzk3NTA2NzgwMjhlKzIzLDEsMDowOjA6MDoxOiA0NzM6MjotMzA6NDUyOjA6MDowITExMDA6NTotNDM6MTcwOjA6MDowITU5OTg6MTo0OToyNDM6MDowOjAhMzQxODowOi0xOTo0MDE6MDowOjAhNzUwOToxOjUxOjE1NzowOjA6MCE4NDU0OjE6NTg6MTY3OjA6MDowITk5MDg6MTo1ODoxNjc6MDowOjAhMTAyNTQ6NTozMTo1NzU6MDowOjAhNjQ5ODoyOi0zNDozMTc6MDowOjAhNjg0NzoyOi01ODozMzowOjA6MCE3NjIxOjI6LTYwOjQxMjowOjA6MCExMTkzOTo1Oi03NToyNjI6MDowOjAhMTU0ODo0Oi0xNzk6MTY4OjA6MDowITE0Mjk4OjE6MTU6MjQxOjA6MDowITYzMzA6NDotMTcwOjI3MTowOjA6MCExNjQxNzoxOjI1OjIzMDowOjA6MCEgMCwxLDI2NjsyNDYsMjQ2LDUuNjg0NDg2MTY3NTA3NzYzZSsyMywxLDgvNC83IDMgMTYxNjQwOTA0MDM5MiAxLDAsMjQ2OzIyOCwyMjgsMi4wOTI0MDgxNzQ1NzkxMzY3ZSsyNSwxLDcxIDQgMjU1IDEsMCwyMjg7MjA4LDIwOCw4LjQ5MDU2NzcwNDU0MTI3OWUrMjQsMCwsMSwyMDg7MTg4LDE4OCw2LjY0OTgyMjg4MzUzMDg0OGUrMjQsMCwsMSwxODg7MTc2LDE3Niw0LjE4NDgzNTQwNTczMTM1OWUrMjUsMSwsMSwxNzY7MTU3LDE1NywxLjA1NjUxMTgxMzc2NTMzNzZlKzI2LDAsLDEsMTU3OzE0NSwxNDUsNi4xMTc0MDAwNTExNTYyNTllKzI2LDAsLDEsMTQ1OzE1NywxNTcsMi4xNzI0MDMyNjA4NDE3NTM3ZSsyOCwwLCwxLDE1NzsxMzQsMTM0LDIuMTM5NjcwMzM2Mjk0MzgyNGUrMjgsMCwsMSwxMzQ7MTI5LDEyOSwxLjI5NzA4NjE4MjU4NzU1MThlKzI5LDAsLDEsMTI5OzEwNiwxMDYsMy42MjM0MjgxMzAyNzgzNzVlKzI5LDAsLDAsMTA2Ozc3LDc3LDEuMjAxOTgyNTUxNDQ2MDQ5MWUrMzAsMCwsMCw3Nzt8MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMTExMTExMTEwMDExMTExMTAwMDAwMDExMDAxMTExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMTEwMDExMTEwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAxMDEwMDAxMTExMDAxMTExMTExMTExMTExMTExMTExMTAwMTExMTExMTExMTExMTEwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMDAwMDExMTExMTExMDAwMDAwMTExMTExMTExMTAwMTExMTExMTExMTExMTExMTAwMDAwMDAwMDAxMTExMTExMTExMDAwMDAwMDAwMDAwMDAwMDExMTExMDExMTEwMDExMTExMTAwMDAxMDExMTAwMDAwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMTExMDExMTExMTExMTExMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAxMTAwMTEwMDExMDAwMDAwMDAwMDExMTExMTExMTExMTExMDAwMDAwMTExMTAwMTAxMTExMTExMTExMTEwMDAwMDAxMTEwMTAxMTExMTExMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMDAwMTExMDEwMTAxMDAwMDAwMDAwMTAxMDEwMTAxMDAwMDAxMTExMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMTExMTExMTExMTAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTExMDAwMDExMTExMTExMTExMTAwMDAwMDAwMDAwMDExMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMTExMTExMTEwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAxMTExfDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMTExMTExMTAxMTExMTEwMTExMTEwMTEwMDAwMDAxMTExMTEwMDExMTExMTAxMTExMTExMDExMTExMTAxMDExMTExMTExMTExMTExMTEwMTExMTEwMDAwMDExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTEwMDAwMDAwMDAwMTEwMDAxMTExMTEwMDAwMDAwMDAxMTExMDAwMDExMTExMTExMTExMDExMTAwMDAxMTAwMDAwMDAwMDAwMTExMTAwMTAwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExMDAxMTExMDAwMDEwMDAxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTExMTAwMDAwMDAxMDAwMDAwMTAxMTEwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMTEwMDAwMDAwMDAwMDEwMDAwMDEwMDAwMDAwMDB8fENvb2tpZU1vbnN0ZXI6eyJzZXR0aW5ncyI6eyJCb3RCYXIiOjEsIlRpbWVyQmFyIjoxLCJUaW1lckJhclBvcyI6MCwiVGltZXJCYXJPdmVybGF5IjoyLCJCdWlsZENvbG9yIjoxLCJCdWxrQnVpbGRDb2xvciI6MCwiVXBCYXJDb2xvciI6MSwiVXBncmFkZUJhckZpeGVkUG9zIjoxLCJDYWxjV3JpbmsiOjAsIkNQU01vZGUiOjEsIkF2Z0NQU0hpc3QiOjEsIkF2Z0NsaWNrc0hpc3QiOjAsIkNvbG9yUFBCdWxrTW9kZSI6MSwiUFBFeGNsdWRlVG9wIjowLCJQUFNlY29uZHNMb3dlckxpbWl0IjowLCJQUE9ubHlDb25zaWRlckJ1eWFibGUiOjAsIlRvb2xXYXJuQm9uIjoxLCJUaXRsZSI6MSwiR2VuZXJhbFNvdW5kIjoxLCJHQ05vdGlmaWNhdGlvbiI6MCwiR0NGbGFzaCI6MSwiR0NTb3VuZCI6MSwiR0NWb2x1bWUiOjEwMCwiR0NTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzY2LzY2NzE3XzkzMTY1NS1scS5tcDMiLCJGb3J0dW5lTm90aWZpY2F0aW9uIjowLCJGb3J0dW5lRmxhc2giOjEsIkZvcnR1bmVTb3VuZCI6MSwiRm9ydHVuZVZvbHVtZSI6MTAwLCJGb3J0dW5lU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xNzQvMTc0MDI3XzMyNDI0OTQtbHEubXAzIiwiU2VhTm90aWZpY2F0aW9uIjowLCJTZWFGbGFzaCI6MSwiU2VhU291bmQiOjEsIlNlYVZvbHVtZSI6NDksIlNlYVNvdW5kVVJMIjoiaHR0cHM6Ly93d3cuZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyMS8xMjEwOTlfMjE5MzI2Ni1scS5tcDMiLCJHYXJkRmxhc2giOjEsIkdhcmRTb3VuZCI6MSwiR2FyZFZvbHVtZSI6MTAwLCJHYXJkU291bmRVUkwiOiJodHRwczovL2ZyZWVzb3VuZC5vcmcvZGF0YS9wcmV2aWV3cy8xMDMvMTAzMDQ2Xzg2MTcxNC1scS5tcDMiLCJNYWdpY05vdGlmaWNhdGlvbiI6MCwiTWFnaWNGbGFzaCI6MSwiTWFnaWNTb3VuZCI6MSwiTWFnaWNWb2x1bWUiOjEwMCwiTWFnaWNTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzIyMS8yMjE2ODNfMTAxNTI0MC1scS5tcDMiLCJXcmlua2xlck5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJGbGFzaCI6MSwiV3JpbmtsZXJTb3VuZCI6MSwiV3JpbmtsZXJWb2x1bWUiOjEwMCwiV3JpbmtsZXJTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzEyNC8xMjQxODZfODA0My1scS5tcDMiLCJXcmlua2xlck1heE5vdGlmaWNhdGlvbiI6MCwiV3JpbmtsZXJNYXhGbGFzaCI6MSwiV3JpbmtsZXJNYXhTb3VuZCI6MSwiV3JpbmtsZXJNYXhWb2x1bWUiOjEwMCwiV3JpbmtsZXJNYXhTb3VuZFVSTCI6Imh0dHBzOi8vZnJlZXNvdW5kLm9yZy9kYXRhL3ByZXZpZXdzLzE1Mi8xNTI3NDNfMTU2NjMtbHEubXAzIiwiVG9vbHRpcEJ1aWxkVXBncmFkZSI6MSwiVG9vbHRpcEFtb3IiOjEsIlRvb2xXYXJuTHVja3kiOjEsIlRvb2xXYXJuTHVja3lGcmVuenkiOjEsIlRvb2xXYXJuQ29uanVyZSI6MSwiVG9vbFdhcm5Db25qdXJlRnJlbnp5IjoxLCJUb29sV2FybkVkaWZpY2UiOjEsIlRvb2xXYXJuVXNlciI6MCwiVG9vbFdhcm5Qb3MiOjEsIlRvb2x0aXBHcmltIjoxLCJUb29sdGlwV3JpbmsiOjEsIlRvb2x0aXBMdW1wIjoxLCJUb29sdGlwUGxvdHMiOjEsIkRyYWdvbkF1cmFJbmZvIjoxLCJUb29sdGlwQXNjZW5kQnV0dG9uIjoxLCJTdGF0cyI6MSwiTWlzc2luZ1VwZ3JhZGVzIjoxLCJVcFN0YXRzIjoxLCJUaW1lRm9ybWF0IjowLCJEZXRhaWxlZFRpbWUiOjEsIkdyaW1vaXJlQmFyIjoxLCJIZWF2ZW5seUNoaXBzVGFyZ2V0IjoxLCJTaG93TWlzc2VkR0MiOjEsIlNjYWxlIjowLCJTY2FsZURlY2ltYWxzIjoyLCJTY2FsZVNlcGFyYXRvciI6MCwiU2NhbGVDdXRvZmYiOjk5OTk5OSwiQ29sb3JzIjp7IkJsdWUiOiIjNGJiOGYwIiwiR3JlZW4iOiIjMDBmZjAwIiwiWWVsbG93IjoiI2ZmZmYwMCIsIk9yYW5nZSI6IiNmZjdmMDAiLCJSZWQiOiIjZmYwMDAwIiwiUHVycGxlIjoiI2ZmMDBmZiIsIkdyYXkiOiIjYjNiM2IzIiwiUGluayI6IiNmZjE0OTMiLCJCcm93biI6IiM4YjQ1MTMifSwiU29ydEJ1aWxkaW5ncyI6MCwiU29ydFVwZ3JhZGVzIjowLCJHQ1RpbWVyIjoxLCJGYXZpY29uIjoxLCJXcmlua2xlckJ1dHRvbnMiOjEsIkJ1bGtCdXlCbG9jayI6MCwiSGVhZGVyIjp7IkJhcnNDb2xvcnMiOjEsIkNhbGN1bGF0aW9uIjoxLCJOb3RpZmljYXRpb24iOjEsIk5vdGlmaWNhdGlvbkdlbmVyYWwiOjEsIk5vdGlmaWNhdGlvbkdDIjoxLCJOb3RpZmljYXRpb25GQyI6MSwiTm90aWZpY2F0aW9uU2VhIjoxLCJOb3RpZmljYXRpb25HYXJkIjoxLCJOb3RpZmljYXRpb25NYWdpIjoxLCJOb3RpZmljYXRpb25XcmluayI6MSwiTm90aWZpY2F0aW9uV3JpbmtNYXgiOjEsIlRvb2x0aXAiOjEsIlN0YXRpc3RpY3MiOjEsIk5vdGF0aW9uIjoxLCJNaXNjZWxsYW5lb3VzIjoxLCJMdWNreSI6MSwiQ2hhaW4iOjEsIlNwZWxscyI6MSwiR2FyZGVuIjoxLCJQcmVzdGlnZSI6MSwiV3JpbmsiOjEsIlNlYSI6MSwiTWlzYyI6MSwiSW5mb1RhYiI6MX0sIlBQRGlzcGxheVRpbWUiOjAsIlRvb2x0aXBQYW50aGVvbiI6MSwiSGlkZVNlY3Rpb25zQnV0dG9ucyI6MCwiUFBSaWdpZGVsTW9kZSI6MH0sInZlcnNpb24iOiIyLjAzMS42In07%21END%21
```

**Comment by DanielNoord** [comment] 2021-03-22 11:12
Duplicate of #703.
We changed the code to now also consider the other columns at all time. In your save you will see there is an optimal option in the "buy 10" column.

**Closed by DanielNoord** 2021-03-22 11:12 UTC
Labels: Bug
