### ISSUE TITLE
Option to calculate Time Left taking "Lucky" deficit into account

### ISSUE THREAD

**Issue by orangy** [Aktanusa/CookieMonster#87] opened 2016-05-02 21:36 UTC
When not idling, it would be nice to see time left for specific purchase taking Lucky GC reserve into account.

**Comment by JCBourgo** [comment] 2016-05-02 21:57
@Aktanusa Add a config to have the calculations take the reserve into account? That's something doable.

**Comment by Aktanusa** [comment] 2016-05-02 23:21
I think this is a duplicate of Issue #67 ?  Let me know if I'm wrong.

**Comment by orangy** [comment] 2016-05-02 23:30
Yep, indeed, looks like duplicate. Sorry to bother.

**Comment by Aktanusa** [comment] 2016-05-03 00:48
Nah, it pushes me to get to it, lol

**Comment by DanielNoord** [comment] 2020-11-26 10:07
This is a duplicate of #67

**Closed by DanielNoord** 2020-11-26 10:07 UTC
Labels: duplicate, enhancement
