### ISSUE TITLE
Update favicon when there's a golden cookie

### ISSUE THREAD

**Issue by CrackedP0t** [Aktanusa/CookieMonster#55] opened 2016-02-17 05:20 UTC
It would be really useful to be able to see if there's a golden cookie by looking at the tab's favicon.

**Comment by Aktanusa** [comment] 2016-02-17 23:20
This is a duplicate of Issue #44.  I'm not too sure how hard it is to do this.

**Comment by svschouw** [comment] 2016-02-17 23:46
The hardest part is probably to create the actual icons. After that I'm guessing that it's just a matter of injecting/updating the <link rel="shortcut icon"/> header. See also http://stackoverflow.com/questions/260857/changing-website-favicon-dynamically

**Comment by Aktanusa** [comment] 2016-02-18 03:08
Yep, any takers on creating the icons?

**Comment by BlackenedGem** [comment] 2016-02-19 18:32
I've taken the existing golden/wrath cookie textures and created icons: http://www.mediafire.com/download/1ly68jae5591upp/favicon.zip
I think it would work quite well, because they're similar to the existing favicon, but with a yellow or red tint to signify the type of cookie that spawned.

**Comment by Aktanusa** [comment] 2016-02-19 20:34
Thanks a lot!  Now I got no excuse not to do it, lol.  Probably tonight, or tomorrow the latest.

**Comment by Aktanusa** [comment] 2016-02-20 01:07
I don't think it be a problem, but your icons are 64x64 vs the 16x16 I think it's suppose to be.

**Comment by BlackenedGem** [comment] 2016-02-20 01:17
The .ico files contain multiple resolutions (including x16). I took the source images (supplied in the folder) and ran them through a png to ico program. Most image viewers should recognise that there are multiple images. Eg. open the file in Windows Photo Viewer and at the bottom you can go through each image). I'm not sure if you will have to specify which size you want to display, but hopefully the browser should automatically pick the best resolution from the different sets.

**Comment by Aktanusa** [comment] 2016-02-20 01:20
Ah, good to know, thanks!

**Comment by Aktanusa** [comment] 2016-02-20 04:29
Added in Version 2.3

**Closed by Aktanusa** 2016-02-20 04:29 UTC
Labels: duplicate, enhancement
