### ISSUE TITLE
Cookies required for Lucky/Chain max reward in any scenario

### ISSUE THREAD

**Issue by Kidsheldon** [Aktanusa/CookieMonster#109] opened 2016-08-18 22:31 UTC
I would like to have a tab for calculating the  max Lucky/Chain reward with whatever multiplier you want to know. Say, for a crazy example, you have Distilled Essence of Redoubled Luck, and you want to know the max reward and bank requirement for Lucky in a Dragon Harvest x Elder Frenzy, in case you get both an Elder Frenzy and a Lucky from 2 GCs during a Dragon Harvest. All you would have to do is calculate the multiplier and type it into a box (in this case, it would be 666 x  15 = 9990x multiplier) and CM will tell you the requirement and reward for that scenario.

**Comment by Aktanusa** [comment] 2016-08-19 03:45
It's true that with the revamp of GC, and a chance of double GC, there are a lot more scenarios.  Because of that, I may have to just make it an option to put whatever you want or something, lol.

**Comment by Anahkiasen** [comment] 2017-07-31 13:33
Would love this too

**Comment by Aktanusa** [comment] 2017-07-31 13:35
I'll get around to it soon, I hope.  I think I finally figured out a good way to make more time (I hope again).

**Comment by DanielNoord** [comment] 2020-11-26 10:30
Duplicate of #105

**Closed by DanielNoord** 2020-11-26 10:30 UTC
Labels: enhancement
