### ISSUE TITLE
Display Effect of Golden/Wrath cookie

### ISSUE THREAD

**Issue by Kittymayor42** [Aktanusa/CookieMonster#599] opened 2021-02-23 04:41 UTC
I'd love to see a tooltip where when you hover your cursor over a golden or wrath cookie, it tells you what the effect is. It would be very helpful for those in the grandmapocalypse (looking for elder frenzies, etc) and can be helpful for which cookies you might want to click. I know when you mouse over the sugar lump, it tells you what type is growing, but I don't know if that's an option for cookies as well.

**Comment by DanielNoord** [comment] 2021-02-23 08:10
Duplicate of #226.
Although I must say I am more open to the idea now and could look at implementing this in a future version. No promises though, leaving this open to see if other people have opinions about this. 
In the meantime you might like [this](https://www.reddit.com/r/CookieClicker/comments/avjk8j/introducing_fortune_cookie_know_the_outcome_of/)

**Comment by Kittymayor42** [comment] 2021-02-23 08:43
Oh whoops. Didn't realize it was a duplicate. but no worries. just thought id suggest it!

**Comment by dhouck** [comment] 2021-02-27 13:42
This feels *much* too cheaty for me; everything else CM shows is something you can get with information the game shows plus math.  If this is added, it should be disabled by default.

**Comment by mbsaerens** [comment] 2021-03-11 16:00
This is technically not possible. The effect is chosen after the cookie is clicked. It is possible to list all the possible effects, but that would be pretty much a static list. No additional value there.

**Comment by DanielNoord** [comment] 2021-03-13 10:08
I have not looked into this, but I believe this is possible, right?
There are other mod which can do this. Or are they only able to predict "FHoF" cookies and not normally spawned cookies?

**Comment by mbsaerens** [comment] 2021-03-13 15:07
For v2.031, the code for clicking a golden gookie starts at line 4549 of main.js?v=2.089

`Game.shimmer.prototype.pop=function(event)//executed when the shimmer is popped by the player`

The actual effects selection starts on line 4748

`					//select an effect
					var list=[];
`

It starts with an empty list and decides whether or not to add an effect. Even the random ones. 

I don't see how you can tell the outcome of the golden cookie with certainty when you don't even know what the possibillities will be. I guess the prediction of FtHoF is more a "most likely" than an actual certainty.

**Comment by DanielNoord** [comment] 2021-03-17 07:36
[FthoF planner](http://fthof-planner.s3-website.us-east-2.amazonaws.com) seems to indicate that you can only reliably predict the Golden Cookie for FthoF and not for any normal cookies.
Considering that and considering that I am still not really sure this functionality fits Cookie Monster I have decided to not implement this. For people that want this functionality I recommend taking a look at the [mods of klattmose](https://github.com/klattmose/klattmose.github.io).

**Closed by DanielNoord** 2021-03-17 07:36 UTC
Labels: Enhancement
