### ISSUE TITLE
[Steam Version] Aura slot from dragon freezes game.

### ISSUE THREAD

**Issue by scaredtodeaf** [Aktanusa/CookieMonster#967] opened 2021-09-04 02:32 UTC
Hi, As soon you unlock the aura slot from the dragon, the game freezes.

**Comment by Reaver01** [comment] 2021-09-04 05:01
![image](https://user-images.githubusercontent.com/1864450/132083080-f229ed68-fea2-4033-b531-921e74c4791b.png)
Here's a dev console screen

Dragon.js
![image](https://user-images.githubusercontent.com/1864450/132083103-5b47bf1d-1d0e-4c4d-b78f-83f099cbabf6.png)

**Comment by DanielNoord** [comment] 2021-09-04 13:41
This is a duplicate of #960

**Closed as completed by DanielNoord** 2021-09-04 13:41 UTC
Labels: Bug
