### ISSUE TITLE
Heavenly chips MAX/Reset bonus income wrong due to wrinklers?

### ISSUE THREAD

**Issue by sunfall** [Aktanusa/CookieMonster#248] opened 2019-04-10 06:53 UTC
With my current save, Cookie Monster says that I'll get ~705 billion heavenly chips (with Skruuia in the Diamond slot, etc.)  However, actually putting Skruuia in the Diamond slot and popping even one wrinkler causes the prestige numbers to plummet dramatically; actually popping them all, selling buildings, and so on results in only 560 billion or so chips.  I'm not sure what's going wrong here.

Save file attached.
[RaarBakery.txt](https://github.com/Aktanusa/CookieMonster/files/3062347/RaarBakery.txt)

**Comment by Aktanusa** [comment] 2019-04-10 13:17
Did you remember to change it to Earth Shatterer?

**Comment by sunfall** [comment] 2019-04-10 14:07
Earth Shatterer doesn't affect the popping of wrinklers, does it?  In any event, yes, in my testing I both put up a Diamond Skruuia and switched one of my auras to Earth Shatterer before starting the procedure.  You can see the numbers drop before selling even a single building.  Attached is an updated save with the appropriate god and aura slotted; all that's needed to test is to pop a single wrinkler and watch the expected numbers drop.
[RaarBakery-2.txt](https://github.com/Aktanusa/CookieMonster/files/3064185/RaarBakery-2.txt)

**Comment by Aktanusa** [comment] 2019-04-10 14:12
No, it doesn't affect it, but right now I don't see it being an issue if popping one drops as long as in the end after you ascent, the calculated number is correct.  You're saying this is not the case, so I'll take a look.

**Comment by sunfall** [comment] 2019-04-10 14:16
Yup, definitely not the case; if I ascend with this save after doing All the Right Things I'm nowhere near 700 billion heavenly chips.  At the moment it puts me at 564.26 billion.

**Comment by Aktanusa** [comment] 2019-04-13 17:55
So looking at it a little bit, I think I do see a bug.  I'll make it as a bug once I've confirmed it.  Thanks for noticing!

**Comment by DanielNoord** [comment] 2020-11-26 11:06
This seems to be related to #347 
Closing it for now

**Closed by DanielNoord** 2020-11-26 11:06 UTC
Labels: bug
