### ISSUE TITLE
Display gains/losses from selling stock

### ISSUE THREAD

**Issue by TakGalaman** [Aktanusa/CookieMonster#595] opened 2021-02-21 17:43 UTC
When I buy a stock or stocks store information about the cost basis (what I paid).
When hovering over the sell button let me know what the net change in my cookies would be if I sold that number of that stock.

**Comment by DanielNoord** [comment] 2021-02-21 18:59
Duplicate of  #307 and similar to #363.
We decided that this is not something that fits well within CookieMonster.
See discussions in those issues for some more arguments and explanation.

**Closed by DanielNoord** 2021-02-21 18:59 UTC
Labels: Enhancement
