### ISSUE TITLE
Cookie Monster conflicts with content mods

### ISSUE THREAD

**Issue by staticvariablejames** [Aktanusa/CookieMonster#332] opened 2020-11-23 19:32 UTC
If a mods adds upgrades and achievements after Cookie Monster loads, then `CM.Sim.Upgrades[i]` and `CM.Sim.Achievements[i]` in `CM.Sim.CopyData` might be `undefined`, triggering a crash.

This is particularly problematic with mods that use [Klattmose's CCSE](https://github.com/klattmose/klattmose.github.io/tree/master/CookieClicker/CCSE-POCs), like [American Season](https://klattmose.github.io/CookieClicker/AmericanSeason.js) and my own [Spiced Cookies](https://github.com/staticvariablejames/SpicedCookies), because CCSE finishes injecting hooks hundreds of milliseconds after it finishes loading. This interval is long enough for Cookie Monster to load, so simply setting Cookie Monster to load last is not enough.

**Comment by DanielNoord** [comment] 2020-11-23 19:54
I am not sure what the best approach to solving this.
Obviously we could add a delay to `CM.Sim.CopyData`, but to me that seems to be a work-around without actually solving the problem. Maybe somebody else has any good ideas. 
Have you tried using CCSE's delayed loading option? Does that help?

**Comment by staticvariablejames** [comment] 2020-11-23 22:04
Simply delaying mod loading will not fix the issue; Cookie Monster will still crash if any player decides to load a content mod after it.

Perhaps adding a guard for `undefined` there would solve the issue? I am not familiar with Cookie Monster's code base, but it seems that the only places that both `Game.Upgrades` and `CM.Sim.Upgrades` are referenced are on `CM.Sim.CopyData`, `CM.Sim.InitData` and `CM.Sim.BuyUpgrades`, and the latter calls `CM.Sim.CopyData`, so simply adding
```javascript
if (you == undefined) {
    CM.Sim.Upgrades[i] = {bought: me.bought};
}
```
should be enough.

A similar procedure can be adopted for the achievements and buildings as well.

Side-note: `CM.Sim.BuyUpgrades` calls `CM.Sim.CopyData` repeatedly inside the loop, is this intended?

**Comment by DanielNoord** [comment] 2020-11-23 22:33
I have only started looking into the code of CM as of today, so I must confess I am also not totally sure what the reasoning behind `CM.Sim.CopyData` is and why it is called repeatedly.

I have just rewritten a significant portion related to another issue so I will get back to you and this issue.
At the moment your suggestion seems fine, so I will certainly consider it.

**Comment by Aktanusa** [comment] 2020-11-23 22:37
It is intended as I never modify the original data.  So each time I need to simulate a buy, I need to copy the original data first and then do the simulation.

**Comment by DanielNoord** [comment] 2020-11-24 11:43
As you can see in #335 I think I have now resolved all issues.
I will leave this issue open for a bit, while @staticvariablejames can test if this has solved all issues and other mod-creators can also chip in.

You can use the code found in the dev-branch or us the following link:
https://danielnoord.github.io/CookieMonster/CookieMonster.js

**Comment by staticvariablejames** [comment] 2020-11-25 06:25
I poked around and found two issues.

First, Cookie Monster still chokes once if players load content mods, because `you` is still `undefined` in `CM.Sim.CopyData` after the conditional.

Second, CM crashes if new buildings are added (e.g. Klattmose's [Black Hole Inverter](https://klattmose.github.io/CookieClicker/CCSE-POCs/BlackholeInverter.js)) because the column for the new building in the bottom bar (`CM.Disp.BotBar`) is missing.

I implemented fixes [here](https://github.com/Aktanusa/CookieMonster/compare/6922dd04653b8ebfaaf614f22dfda5b4d3fc0b96...staticvariablejames:4d23275441dd1f0e8639d9e84188a1e8d9917ce6). This allows buildings to be added after CM loads and have it still predict everything nicely. Should I submit a pull request?

**Comment by DanielNoord** [comment] 2020-11-25 07:53
At first glance this looks good. I will need to see if the code clashes with the implementation of #277, which I hope to do in the near-future. But if it does I can easily change it.

However, I am wondering if the call to `CM.Disp.CreateBotBarBuildingColumn` is in the "right" place.
Maybe it would be better to do this elsewhere? As in, make a general call in the main loop that checks for any changes to the data? Placing it under `CM.Sim.CopyData` seems logical, but it kind of hides a function that seems to belong to a higher level of general functions.
What do you think?

**Comment by staticvariablejames** [comment] 2020-11-25 19:48
The implementation of #277 will technically clash with this, but only to the extent that `CM.Disp.CreateBotBarBuildingColumn` has to be changed as well. The call in `CM.Sim.CopyData` can be left intact.

Calling `CM.Disp.CreateBotBarBuildingColumn` in `CM.Sim.CopyData` indeed feels hidden. I annotated that method [here](https://github.com/staticvariablejames/CookieMonster/commit/71906667f872285dc63068e95bf40b5d8bd1114c) to mitigate this.

I don't think that having a method checking for changes is a good idea. We essentially have the invariant that every building in `Game.Objects` is "registered" in CM (exists in `CM.Sim.Objects`, `CM.Cache.Objects` and in `BotBar`). The only place in the code that can discover that this invariant is broken is in `CM.Sim.CopyData`, so by calling `InitData` and `CreateBotBarBuildingColumn` the invariant is reestablished. My worry of decoupling this is that every place in the code that calls `CopyData` will have to ensure the invariant.

Alternatively, Cookie Monster could expose a `CM.RegisterBuilding(name)` function that would take care of maintaining the invariant, and then other mods have to explicitly add compatibility with Cookie Monster by calling this method.

**Comment by DanielNoord** [comment] 2020-11-25 20:51
Yes, I agree. And as `CM.Loop` calls `CM.Cache.RemakeIncome` > `CM.Sim.BuyBuildings` > `CM.Sim.CopyData();` it gets called on every loop.
We might want to add a comparison between `CM.Sim.Objects` and `Game.Objects` in the main loop to show that this does get checked on every loop, but functionally it would be the same. Perhaps we want to add this later on as other issues arise, but for now I think this is fine.

Therefore, I think you can go ahead and make a pull request.

**Comment by DanielNoord** [comment] 2020-11-26 17:10
Although #350 fixes the problem a new problem has now emerged (although related, therefore I have not openend a new issue).
Whenever I load CookieMonster and subsequently SpicedCookies (through the console) the PP calculation freezes and indicates that cursors have a PP of infinity.
Have not looked into this sufficiently but something is making the PP calculation choke for a couple of seconds.

[Save file](https://github.com/Aktanusa/CookieMonster/files/5604321/ProfessorCookBakery.1.txt) in case you are unable to reproduce this.
@staticvariablejames any idea what is happening? Or do you have time to check this bug out?

**Comment by staticvariablejames** [comment] 2020-11-27 01:10
I was able to reproduce it in a fresh save. Some experimentation shows that the problem happens precisely because Spiced Cookies adds a new debug upgrade. The same thing happens with e.g. Klattmose's [American Season](https://klattmose.github.io/CookieClicker/AmericanSeason.js). I will see if I can figure out what's going on inside Cookie Monster.

On a separate note, you squashed all the seven commits from my pull request into a single one. Is there any reason?

**Comment by staticvariablejames** [comment] 2020-11-27 02:56
Silly mistake. By calling `CM.Sim.InitData` if `you == undefined`, we accidentally erase all the data copied in the previous lines of `CM.Sim.CopyData`.

I implemented a fix [here](https://github.com/staticvariablejames/CookieMonster/commit/be865da52a949590af25ca20e882670c1da8db9e).

**Comment by DanielNoord** [comment] 2020-11-27 07:35
I squashed all commits as we like to keep the commit history of the dev and master branch fairly clean.
As many new or less experienced users tend to look at this repository keeping the commit log clean makes it all less daunting.
If they want to further inspect a commit they can then look at the actual PR and see what was changed.
Maybe this is not common practice for most repositories, but personally I like this practice.

Good catch on the bug. As I said I had not really inspected it myself, but good work!
Can you make a PR for the fix?

The funny thing is that we actually have an issue related to NaN, see #156 
Thanks for noticing the source of the error. However, I do agree with the discussion in that issue;
NaN looks as if something has happened that was unexpected and it is better to than put a 0 of N/A there.
I will look at both issues at the same time and see what is the best way to fix it. 
I can always change NaN to become N/A or 0 and then tell the sorting function to consider those as very high values.

**Comment by staticvariablejames** [comment] 2020-11-27 17:53
Squashing commits this way goes against all "Git best practices" guides I've came across, which recommend preferring small commits to large commits. It also destroys part of the history; for example, one of the commits that got squashed simply marked `Combine.sh` as executable, whereas now it seems that this change was part of the bugfix.

I create a pull request (<https://github.com/Aktanusa/CookieMonster/pull/356>) based on the existing `dev` branch, but would gladly rewrite it to include it with the original sequence of commits.

**Comment by DanielNoord** [comment] 2020-11-28 09:21
Ah okay, I am sorry I must confess this is on of the first times I am using GitHub in a collaborative effort.

When I started on this project I found many of the commits and pull request very unclear. Both lacking in clear titles but also fixing issues in small steps/commits making it difficult to get to grasp with the project timeline.
This is why I started squashing commits to make the commit log more insightful for those who might work on this in 2 or 4 years time (some of the original code was written in 2014).

However, I agree that I have been a little bit too diligent and might have squashed commits that should have ultimately been left separate. In the future I will be more cautious.

#356 is fine and I do not want to ask much more of you. You have already done a whole lot for the project in the last couple of days, both in terms of code and helping us new maintainers find our way in the project. This is much appreciated!

**Comment by staticvariablejames** [comment] 2020-11-28 14:46
No problem! I hope you don't mind I keep poking around :)

Good point on the project timeline. I'm also new on this stuff, so I'm not sure how to reconcile having a cleaner history with keeping commits small.

One possibility would be appending issue numbers to all commits in the repository; for example, all commits I contributed to this one should end in `(#332)`. Then using rebase instead of merge would allow for a linear history, but still allowing future contributors to know which commits are related to which features. This would also mean that every new fix/feature would have to first be recorded as a GitHub issue, which is not a bad thing.

[Here](https://github.com/staticvariablejames/CookieMonster/tree/rebase-dev) I implemented the fix as a rebase on top of `dev`, if you'd like to take a look.

**Comment by DanielNoord** [comment] 2020-11-28 14:48
I certainly don't mind, it is much appreciated!

Yeah, I think together we all need to find a way that works best. Good call on including issue numbers in the commits, I will take care to do this from now on.

Do you agree with me that we can now close this issue? Or have you found any other related problems?

**Comment by Aktanusa** [comment] 2020-11-28 14:57
Off topic: My bad, I should have added that to guidelines.  To commit with the Issue number.  I'll do that now.

**Comment by staticvariablejames** [comment] 2020-11-28 15:17
I think that for now this issue can be closed.

There are a few content mods in development that might end up conflicting with Cookie Monster again, but we can discuss the conflicts when they happen. (The discussion of them happens mostly on Discord; feel free to join us there!)

**Comment by DanielNoord** [comment] 2020-11-28 15:18
Good, then I'll close it!

Not really a discord user myself, but perhaps I will take a look in the near future. If any other problems arise I am usually quick to respond to new issues!

**Closed by DanielNoord** 2020-11-28 15:18 UTC
Labels: bug
