### ISSUE TITLE
[2.031] Update to include new upgrades and cookies

### ISSUE THREAD

**Issue by Jollto** [Aktanusa/CookieMonster#317] opened 2020-11-02 08:20 UTC
With the new update, there are some upgrades and heavenly upgrades that make the PP calculator show negative numbers, and this breaks the use of the program.
[JolltoBakery.txt](https://github.com/Aktanusa/CookieMonster/files/5473566/JolltoBakery.txt)

**Comment by FWDekker** [comment] 2020-11-02 16:31
This is a duplicate of #302, just like #306 and #310.

**Comment by VincentThierry** [comment] 2020-11-03 12:17
@FWDekker I don't this is a duplicate, just a similar issue. They are most likely talking about the "Milkhelp lactose intolerance relief tablets" heavenly upgrade, which also breaks the numbers. The other issues are only talking about the "Dragon Scale" upgrade.

**Comment by FWDekker** [comment] 2020-11-03 13:55
@VincentThierry  Yeah fair I suppose you could divide that into two issues. Either way I think it's good to link these issues together so that people that encounter the same issues know where to look for solutions.

**Comment by chiffon-rouge** [comment] 2020-11-05 21:22
Great, there is a fix already, though Aktanusa has yet to accept the pull request (please do!)

**Comment by DanielNoord** [comment] 2020-11-23 17:29
With the update to 2.031.1 this has now been resolved!

**Closed by DanielNoord** 2020-11-23 17:29 UTC
