### ISSUE TITLE
Suggestion: For upgrades that increase clicking power, show how much they increase per click

### ISSUE THREAD

**Issue by jaketheboss888** [Aktanusa/CookieMonster#301] opened 2020-08-07 18:24 UTC
For upgrades that increase clicking power, insted of showing 0 for bonus income it could show how much it increases for each click

**Comment by DanielNoord** [comment] 2020-11-26 11:19
This is a duplicate of #231 and #254

**Closed** 2020-12-18 22:25 UTC
Labels: Enhancement
