### ISSUE TITLE
[Question] How many purchases of does your PP-value look ahead?

### ISSUE THREAD

**Issue by strauss** [Aktanusa/CookieMonster#114] opened 2017-03-06 10:05 UTC
My observation suggests that only the next purchase of a building is considered for the PP calculation. E.g., I want to have the 100 Grandma achievement for raising my milk and have bought up to 98 grandmas. The building color key turned deep red. If I buy the 99th grandma it suddenly turns green because CookieMonster detects the achievement that comes with the purchase of the 100th grandma.

It would be great if CookieMonster would detect that earlier. However, I have no idea how this can be calculated into the PP-value.

**Comment by Aktanusa** [comment] 2017-03-06 15:40
This is what Issue #4 is going to add.

**Comment by strauss** [comment] 2017-03-09 21:23
Sorry for the duplicate.

I really like your addon. Keep on the great work <3

**Comment by Aktanusa** [comment] 2017-03-09 21:25
Thanks, though this would prob be a while since it is a bit of work.  Sorry.

**Comment by DanielNoord** [comment] 2020-11-26 09:46
This is indeed a duplicate of #4

**Closed by DanielNoord** 2020-11-26 09:46 UTC
Labels: duplicate, enhancement
