### ISSUE TITLE
Game screen freezes

### ISSUE THREAD

**Issue by Damaskox** [Aktanusa/CookieMonster#554] opened 2021-02-06 06:26 UTC
After loading CookieMonster and opening stats tab, everything freezes within seconds (for no apparent reason). The buttons can be pushed after freeze-up (save game, buy buildings), but even when saving within freeze-up and refreshing the page, the changes after freeze-up have been unsaved.
Even swapping for a second to the stats tab and then away will soon enough freeze everything.

Dunno what specs you need, but I'll post something:

![kuva](https://user-images.githubusercontent.com/76251763/107110960-bea5a380-6854-11eb-9fe4-84a357eefd76.png)

![kuva](https://user-images.githubusercontent.com/76251763/107110972-da10ae80-6854-11eb-95b2-5070fe7883fb.png)

**Comment by DanielNoord** [comment] 2021-02-06 08:49
This is a know problem and a duplicate of #528.
Until I fix it the only thing that helps is turning of "Show missing upgrades" until you are somewhat further in the game.
It breaks because the code does not handle saves without any upgrades correctly. So as soon as you have an upgrade of every type it checks for you will be fine! Sorry for the inconvenience in the meantime.

**Closed by DanielNoord** 2021-02-06 08:49 UTC

**Comment by Damaskox** [comment] 2021-02-06 12:00
> 
> 
> This is a know problem and a duplicate of #528.
> Until I fix it the only thing that helps is turning of "Show missing upgrades" until you are somewhat further in the game.
> It breaks because the code does not handle saves without any upgrades correctly. So as soon as you have an upgrade of every type it checks for you will be fine! Sorry for the inconvenience in the meantime.

Okay, found the option and disabled it. Thank you!

**Comment by DanielNoord** [comment] 2021-02-17 21:51
The problem should be fixed now and you can turn on Missing Upgrades again!
Please do tell if any problems remain!

**Comment by Damaskox** [comment] 2021-04-10 18:31
Yes, it worked.

---
Now, I think there is another strange thing happening. It seems that I no
longer see any buildings better to be purchased than yellow-coloured. The
same thing goes with upgrades.

I haven't seen this happening before, with this addon. There's always been
at least green ones to be bought among the "worse" colours.

ke 17. helmik. 2021 klo 23.51 Daniël van Noord ***@***.***)
kirjoitti:

**Comment by DanielNoord** [comment] 2021-04-10 18:33
Check the buy x10 column.
There is probably a building with a lower PP value when buying 10 at a time than buying 1 at a time.

**Comment by Damaskox** [comment] 2021-04-10 18:40
I have been on column 1x.
The 10x column showed one green building. 100x and 1x didn't show any green
ones.

la 10. huhtik. 2021 klo 21.33 Daniël van Noord ***@***.***)
kirjoitti:

**Comment by DanielNoord** [comment] 2021-04-10 18:42
The green building is still the most optimal. In this case it is actually better to buy those than buildings than to buy a single other building. You can check this by comparing the PP values. You will see that none of the buildings in the 1x column will have a lower PP than the green building in the 10x column.

**Comment by Damaskox** [comment] 2021-04-10 18:45
Okay. it seems that I need to jump between 1x and 10x all the time to
continue buying the most optimal thing. I haven't seen this happening
before, so I got confused =) I don't usually buy buildings in bulk.

I got one blue upgrade, so that also seems to work (again).

la 10. huhtik. 2021 klo 21.42 Daniël van Noord ***@***.***)
kirjoitti:

**Comment by DanielNoord** [comment] 2021-04-10 18:46
This is a relatively new function. Previously we did not really consider these cases but Cookie Monster now shows you more correct data! :)

**Comment by Damaskox** [comment] 2021-04-10 18:49
Nice!

And a salute for faster-than-bullet replies! =D

la 10. huhtik. 2021 klo 21.46 Daniël van Noord ***@***.***)
kirjoitti:
