### ISSUE TITLE
automatic wrinkler inclusion/exclusion

### ISSUE THREAD

**Issue by The-furf-of-July** [Aktanusa/CookieMonster#247] opened 2019-04-07 20:51 UTC
Is it sometimes more efficient to leave a wrinkler unpopped than to buy an upgrade? I know this is asking for a lot, but, maybe it could be possible to calculate whether it would be more worth popping a certain number of wrinklers and waiting for them to come back instead of waiting until the bank naturally reaches that number. Something could get more efficient the less wrinklers need to be popped to buy it, which affects its impact on cookie generation. This could automate the inclusion of wrinklers in the calculation... but just an idea.

**Comment by The-furf-of-July** [comment] 2019-04-07 20:54
i.e. right now, fractals are listed as the most efficient, though I can't afford it without popping a wrinkler. So if I buy it now, I'd lose some generation due to the loss of a wrinkler. in that case, maybe one of the other buildings is more efficient if I can afford it without losing a wrinkler for it. 
This would need to be a togglable thing of course.

**Comment by Aktanusa** [comment] 2019-04-08 13:13
Similar to #108.

**Comment by The-furf-of-July** [comment] 2019-04-19 08:15
I don't think it's exactly similar, but it definitely is related.

**Comment by The-furf-of-July** [comment] 2019-04-30 01:25
I recently calculated that at 2 wrinkler upgrades and 12 wrinklers, popping a wrinkler loses you 14.725% of your income. It should be possible to calculate the overall reward of popping wrinklers and buying the upgrade, and using that, whether it would be worth popping a given number of wrinklers to get it. If it's still an efficient buy after compensating for the loss of wrinklers, then include them in the countdown.

**Comment by Aktanusa** [comment] 2019-05-02 18:51
Sorry, still lacking time, I'll take a look when I can.

**Comment by DanielNoord** [comment] 2020-11-26 11:04
Duplicate of #106

**Closed by DanielNoord** 2020-11-26 11:04 UTC
Labels: enhancement
