### ISSUE TITLE
"Prestige - Cookies to Next Level" timer doesn't use Calculation settings

### ISSUE THREAD

**Issue by UrzaMTG** [Aktanusa/CookieMonster#132] opened 2017-08-03 12:58 UTC
If the Calculation settings are changed to use Current cookies per second instead of Average cookies per second, the timer for "Cookies to Next Level" used in the Prestige section of the "Cookie Monster Goodies" in the stats still uses the Average CpS for the player.

**Comment by Aktanusa** [comment] 2017-08-03 13:08
Nice catch.  It also seems my tooltip is wrong also...

**Comment by UrzaMTG** [comment] 2017-08-03 18:13
Looks like this applies to all the timers in the Goodies section.

**Comment by Aktanusa** [comment] 2017-08-04 02:28
I'll go check, but I don't think it does...

**Comment by UrzaMTG** [comment] 2017-08-04 02:29
Double checked, you're right, it doesn't. I got confused by some client
side lag causing some seconds to get skipped.

**Comment by Aktanusa** [comment] 2017-08-04 02:35
So I took a closer look, and since this is old code I've done a while ago, I forgot what I was thinking, but it looks like it is by design to always use average for Cookies to Next Level.  This is because Prestige max is calculated with Chocolate Egg, and I gather those stats also for average CPS to figure out how long until the next level including the gain from Chocolate Egg.  I mean I guess I can have the setting use it correctly but I think the time would be really off.

**Comment by Mithandil** [comment] 2017-08-08 15:03
I noticed that the Amount to the nexr Prestige Level displayed in your Statistics differ from the Amount given by the Website.

**Comment by Aktanusa** [comment] 2017-08-08 15:07
you mean by CC?  If you go over the ? part, you will see why.

**Comment by UrzaMTG** [comment] 2017-08-12 14:53
The time in the stats page is already really off when using the average. If I spike my CPS for any reason (frenzy, Click Frenzy, Elder Frenzy, etc), the time shrinks to a tiny number and then sits there for the duration of the averaging period. For example, because of an Elder Frenzy, my Cookies to Next Level timer sat at 2 seconds for several minutes until the CPS spike started to roll out of the average range (which I can't quite determine how long it is for this stat). I should mention I'm still fairly early on in the ascensions; my prestige level is under 1000.

**Comment by Aktanusa** [comment] 2017-08-12 15:15
Hmm, it should say (Past x minute) in the stat.  I plan to change the default setting to be past 1 min, but you can do that manually now via settings.

**Comment by Aktanusa** [comment] 2017-08-17 21:30
Sorry to say, changing it to use current CPS would really be off.  I've changed the default setting to be 1 min, which should fix your problem every min.  I don't think this is a bug anymore, but I'll wait for your reply before I close.

**Comment by Aktanusa** [comment] 2018-04-24 23:06
I'm going to close this due to being idle.

**Closed by Aktanusa** 2018-04-24 23:06 UTC
